---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list 
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: ubuntu
  gather_facts: true

  # Variable: variables that will apply to the play, on all target systems
#  vars:

  # Task: Update the Ubuntu machines
  pre_tasks:
    - name: Check apt last update
      stat:
        path=/var/cache/apt
      register: apt_cache_stat 

  tasks:
    - name: Update Ubuntu machines if required
      apt:
        update_cache: yes
        upgrade: full
        upgrade: dist
        autoclean: yes
        autoremove: yes     
        force_apt_get: true
      when: ansible_distribution == "Ubuntu" #and ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12
      check_mode: no

  post_tasks:  
    - name: Reboot the server if required
      command: shutdown -r +20 'Your system will reboot in 20 minutes to complete the upgrade, kindly save your important work' removes=/var/run/reboot-required
      when:   
      check_mode: no

    - name: Wait for server to reboot
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        state: started
      connection: local
      become: no      
      check_mode: no

# Three dots indicate the end of a YAML document
...
